defaults: &defaults
  serverengine:
    log: 'STDOUT'
    log_level: 'debug'
    log_rotate_age: 5
    log_rotate_size: 10485760
  triglav:
    url: <%= ENV['TRIGLAV_URL'] || 'http://localhost:7800' %>
    credential:
      username: <%= ENV['TRIGLAV_USERNAME'] || 'triglav_test' %>
      password: <%= ENV['TRIGLAV_PASSWORD'] || 'triglav_test' %>
      authenticator: local
    timeout: 60
    debugging: false
    retries: 3
    retry_interval: 3 # sec
  hdfs:
    monitor_interval: 5
    parallel_size: 1 # default: 1
    parallel_type: 'thread' # thread or process. default: thread
    connection_pool_size: 1 # default: same with parallel.size
    connection_pool_timeout: 60 # sec. default: 60
    connection_info:
      "hdfs://":
        config_files:
          # - /etc/hadoop/conf/core-site.xml
          # - /etc/hadoop/conf/hdfs-site.xml
        config:
          fs.defaultFS: <%= "hdfs://#{ENV['HDFS_HOST']}:#{ENV['HDFS_PORT']}" %>
          dfs.replication: 1
          fs.hdfs.impl: 'org.apache.hadoop.hdfs.DistributedFileSystem'
          fs.file.impl: 'org.apache.hadoop.fs.LocalFileSystem'
        doas: hadoop

development:
  <<: *defaults

test:
  <<: *defaults
