language: ruby
cache: bundler
rvm:
  - jruby-9.1.5.0
  - jruby-head
jdk:
  - oraclejdk8
before_install:
  - gem install bundler
script:
  - bundle exec rake vendor_jars
  - bundle exec rake test
matrix:
  allow_failures:
    - rvm: jruby-head
