language: ruby
cache: bundler
rvm:
  - jruby-9.1.5.0
  - jruby-head
jdk:
  - oraclejdk8
env:
  - JAR_DEPENDENCIES_VERSION=0.3.5
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: jruby-head
