language: ruby
cache: bundler
rvm:
  - jruby-9.1.5.0
  - jruby-head
jdk:
  - oraclejdk8
before_install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - env JARS_HOME=vendor/jbundle bundle exec jbundle install
script:
  - env JARS_HOME=vendor/jbundle bundle exec rake test
matrix:
  allow_failures:
    - rvm: jruby-head
